package net.eventhub.domain;
// Generated Jun 11, 2021, 12:30:35 AM by Hibernate Tools 5.4.30.Final

import javax.persistence.*;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "Category")
public class Category implements java.io.Serializable {

	@Id
	@Column(name ="category_id")
	private int id;
	
	@Column(name = "name")
	private String name;
	
	@Column(name = "active")
	private Byte active;
	
	@Column(name = "priority")
	private int priority;

	public Category() {
	}
	

	public Category(int categoryId) {
		this.id = categoryId;
	}

	public Category(int categoryId, String name, Byte active) {
		this.id = categoryId;
		this.name = name;
		this.active = active;
}

	public int getId() {
		return this.id;
	}

	public void setId(int categoryId) {
		this.id = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Byte getActive() {
		return this.active;
	}

	public void setActive(Byte active) {
		this.active = active;
	}


	public int getPriority() {
		return priority;
	}


	public void setPriority(int priority) {
		this.priority = priority;
	}


		
	

}
