package net.eventhub.domain;
// Generated Jun 11, 2021, 12:30:35 AM by Hibernate Tools 5.4.30.Final

import javax.persistence.*;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "event_image")
public class EventImage implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name ="id")
	private int id;
	
	@Column(name = "image_url")
	private String imageUtl;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_id")
	private Event event;
	
	@Column(name = "selected")
	private boolean selected;

	public EventImage() {
	}



	public int getId() {
		return id;
	}



	public void setId(int id) {
		this.id = id;
	}



	public String getImageUtl() {
		return imageUtl;
	}



	public void setImageUtl(String imageUtl) {
		this.imageUtl = imageUtl;
	}



	public Event getEvent() {
		return event;
	}



	public void setEvent(Event event) {
		this.event = event;
	}



	public boolean isSelected() {
		return selected;
	}



	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	

	
	
}
