package net.eventhub.domain;
// Generated Jun 11, 2021, 12:30:35 AM by Hibernate Tools 5.4.30.Final

import javax.json.bind.annotation.JsonbTransient;
import javax.persistence.*;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "event_update")
public class EventUpdate implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name ="id")
	private int id;
	
	@Column(name = "description")
	private String update;
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_id")
	private Event event;
	
	public EventUpdate() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUpdate() {
		return update;
	}

	public void setUpdate(String update) {
		this.update = update;
	}

	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}
	
}
