package net.eventhub.domain;
// Generated Jun 11, 2021, 12:30:35 AM by Hibernate Tools 5.4.30.Final

import javax.persistence.*;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "invitation_status")
public class InvitationStatus implements java.io.Serializable {

	@Id
	@Column(name ="id")
	private int id;
	
	@Column(name = "name")
	private String name;

	public InvitationStatus() {
	}
	

	public InvitationStatus(int id) {
		this.id = id;
	}

	public InvitationStatus(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


}
