package net.eventhub.domain;
// Generated Jun 11, 2021, 12:30:35 AM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.DynamicUpdate;

//import com.fasterxml.jackson.annotation.JsonIgnore; 



/**
 * User generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "user")
public class User implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "user_id")
	private int id;
	
	@Column(name = "display_name")
	private String displayName;
	
	@Column(name="first_name")
	private String firstName;
	
	@Column(name="last_name")
	private String lastName;
	
	@Column(name = "description")
	private String description;
	
	@Column(name = "phone")
	private String phone;
	
	@Column(name = "email")
	private String email;
	
	@Column(name = "gender")
	private String gender;
	
	@Column(name = "major")
	private String major;
	
	@Column(name = "avatar")
	private String avatar;
	
	@Column(name = "website")
	private String website;
	
	@Temporal(value=TemporalType.TIMESTAMP)
	@Column(name = "last_login")
	private Date lastLogin;
	
	@Temporal(value=TemporalType.TIMESTAMP)
	@Column(name = "created_at")
	private Date createdAt;
	
	@Column(name = "disabled", nullable = false, columnDefinition = "boolean default false")
	private Boolean disabled;
	//@ManyToMany(mappedBy = "invitees", fetch = FetchType.LAZY)
	@Transient
	private Set<Event> invitations;
	
	
	//@ManyToMany(mappedBy = "attendees", fetch = FetchType.LAZY)
	@Transient
	private Set<Event> participatedEvents;
	
	
	//@OneToMany(mappedBy = "host", fetch = FetchType.LAZY) 
	@Transient
	private Set<Event> hostedEvents;
	
	
	

	public User() {
	}


	public User(int userId) {
		this.id = userId;
	}

	public User(int userId, String displayName, String email)
	{
		this.id = userId;
		this.displayName = displayName;
		this.email = email;
	}
	
	public int getId() {
		return this.id;
	}

	public void setId(int userId) {
		this.id = userId;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getMajor() {
		return this.major;
	}

	public void setMajor(String major) {
		this.major = major;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	
	
	  
	public String getAvatar() {
		return avatar;
	}


	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}


	public String getWebsite() {
		return website;
	}


	public void setWebsite(String website) {
		this.website = website;
	}

	
	public Boolean getDisabled() {
		return disabled;
	}


	public void setDisabled(Boolean disabled) {
		this.disabled = disabled;
	}


	public Set<Event> getInvitations() {
		return invitations;
	}


	public void setInvitations(Set<Event> invitations) {
		this.invitations = invitations;
	}


	public Set<Event> getParticipatedEvents() {
		return participatedEvents;
	}


	public void setParticipatedEvents(Set<Event> participatedEvents) {
		this.participatedEvents = participatedEvents;
	}


	public Set<Event> getHostedEvents() {
		return hostedEvents;
	}


	public void setHostedEvents(Set<Event> hostedEvents) {
		this.hostedEvents = hostedEvents;
	}

	

}
